version: '3.6'

services:
  docker:
    container_name: dev.aeccelerator.com
    restart: always
    image: nginx
    expose:
      - 80
    volumes:
      - ./dist:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=dev.aeccelerator.com,www.dev.aeccelerator.com

networks:
  default:
    external:
      name: nginx-proxy
